site_name: docs
site_url: https://winuxnomacs.github.io/docs
theme:
  name: material
  features:
    - search.suggest
    - search.highlight
    - navigation.instant
plugins:
  - search
extra:
  consent:
    title: Cookie consent
    description: >-
      We use cookies to recognize your repeated visits and preferences, as well
      as to measure the effectiveness of our documentation and whether users
      find what they're searching for. With your consent, you're helping us to
      make our documentation better.